/*******************************************************************************/
/*  © Université de Lille, The Pip Development Team (2015-2025)                */
/*  Copyright (C) 2020-2025 Orange                                             */
/*                                                                             */
/*  This software is a computer program whose purpose is to run a filesystem   */
/*  with in-place execution and memory isolation.                              */
/*                                                                             */
/*  This software is governed by the CeCILL license under French law and       */
/*  abiding by the rules of distribution of free software.  You can  use,      */
/*  modify and/ or redistribute the software under the terms of the CeCILL     */
/*  license as circulated by CEA, CNRS and INRIA at the following URL          */
/*  "http://www.cecill.info".                                                  */
/*                                                                             */
/*  As a counterpart to the access to the source code and  rights to copy,     */
/*  modify and redistribute granted by the license, users are provided only    */
/*  with a limited warranty  and the software's author,  the holder of the     */
/*  economic rights,  and the successive licensors  have only  limited         */
/*  liability.                                                                 */
/*                                                                             */
/*  In this respect, the user's attention is drawn to the risks associated     */
/*  with loading,  using,  modifying and/or developing or reproducing the      */
/*  software by the user in light of its specific status of free software,     */
/*  that may mean  that it is complicated to manipulate,  and  that  also      */
/*  therefore means  that it is reserved for developers  and  experienced      */
/*  professionals having in-depth computer knowledge. Users are therefore      */
/*  encouraged to load and test the software's suitability as regards their    */
/*  requirements in conditions enabling the security of their systems and/or   */
/*  data to be ensured and,  more generally, to use and operate it in the      */
/*  same conditions as regards security.                                       */
/*                                                                             */
/*  The fact that you are presently reading this means that you have had       */
/*  knowledge of the CeCILL license and that you accept its terms.             */
/*******************************************************************************/

/*
 * libc includes
 */
#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

/*
 * xipfs includes
 */
#include "include/xipfs.h"
#include "include/buffer.h"
#include "include/errno.h"
#include "include/file.h"
#include "include/flash.h"

#ifdef XIPFS_ENABLE_SAFE_EXEC_SUPPORT
#include "include/mpu_driver.h"
#include "include/shared_api.h"
#endif

#if defined(__arm__) || defined(__thumb__)
#define XIPFS_HAS_ARM_EXEC (1)
#else
#define XIPFS_HAS_ARM_EXEC (0)
#endif

/*
 * Macro definitions
 */

/**
 * @internal
 *
 * @def XIPFS_FREE_RAM_SIZE
 *
 * @brief Amount of free RAM available for the relocatable
 * binary to use
 */
//#define XIPFS_FREE_RAM_SIZE (4096)
#define XIPFS_FREE_RAM_SIZE (1024*12)

/**
 * @internal
 *
 * @def EXEC_STACKSIZE_DEFAULT
 *
 * @brief The default execution stack size of the binary
 */
#define EXEC_STACKSIZE_DEFAULT 2048 // 1024

/**
 * @def EXC_RETURN_THREAD_MODE_PSP
 *
 * @brief The exec return adress to return from handler mode
 * to thread mode with psp stack
 */
#define EXC_RETURN_THREAD_MODE_PSP      0xFFFFFFFD

/**
 * @def XPSR_THUMB_MODE
 *
 * @brief The mask used during context switch to set xPSR to thumb mode,
 * it is mandatory to set xPSR to thumb mode to use exec return mechanism
 */
#define XPSR_THUMB_MODE                 0x1000000

#ifdef __GNUC__
/**
 * @internal
 *
 * @def NAKED
 *
 * @brief Indicates that the specified function does not need
 * prologue/epilogue sequences generated by the compiler
 */
#if XIPFS_HAS_ARM_EXEC
#define NAKED __attribute__((naked))
#else
#define NAKED
#endif
/**
 * @internal
 *
 * @def UNUSED
 *
 * @brief Indicates that the specified variable or function may
 * be intentionally unused
 */
#define UNUSED __attribute__((unused))
/**
 * @internal
 *
 * @def USED
 *
 * @brief Indicates that the specified static variable or
 * function is to be retained in the object file, even if it is
 * unreferenced
 */
#define USED __attribute__((used))
#else
#error "sys/fs/file: Your compiler does not support GNU extensions"
#endif /* __GNUC__ */

/**
 * @internal
 *
 * @def STR_HELPER
 *
 * @brief Used for preprocessing in asm statements
 */
#define STR_HELPER(x) #x

/**
 * @internal
 *
 * @def STR
 *
 * @brief Used for preprocessing in asm statements
 */
#define STR(x)        STR_HELPER(x)

/**
 * @internal
 *
 * @brief Structure describing an exception stack frame,
 * used to switch between user / privileged mode
 */
typedef struct {
    /**
     * The r0 register
     */
    uint32_t r0;
    /**
     * The r1 register
     */
    uint32_t r1;
    /**
     * The r2 register
     */
    uint32_t r2;
    /**
     * The r3 register
     */
    uint32_t r3;
    /**
     * The r12 register
     */
    uint32_t r12;
    /**
     * The lr register
     */
    uint32_t lr;
    /**
     * The pc register
     */
    uint32_t pc;
    /**
     * The xPSR register
     */
    uint32_t xpsr;
} isr_stack_frame_t;

/**
 * @internal
 *
 * @brief An enumeration describing the different modes of the control register
 */
typedef enum control_register_mode_e {
    /**
     * Privileged mode with MSP stack
     */
    CTRL_PRIV_MSP = 0,
    /**
     * User mode with MSP stack
     */
    CTRL_USER_MSP = 1,
    /**
     * Privileged mode with PSP stack
     */
    CTRL_PRIV_PSP = 2,
    /**
     * User mode with PSP stack
     */
    CTRL_USER_PSP = 3
} control_register_mode_t;

/**
 * @internal
 *
 * @brief Data structure that describes the memory layout
 * required by the CRT0 to execute the relocatable binary
 * @warning MUST REMAIN SYNCHRONIZED with FAE format and libpip-riot definitions.
 */
typedef struct crt0_ctx_s {
    /*
     * Start address of the binary in the NVM
     */
    void *bin_base;
    /**
     * Start address of the available free RAM
     */
    void *ram_start;
    /**
     * End address of the available free RAM
     */
    void *ram_end;
    /**
     * Start address of the free NVM
     */
    void *nvm_start;
    /**
     * End address of the free NVM
     */
    void *nvm_end;
    /**
     * Arguments passed to the relocatable binary.
     * This is up to caller and callee to agree on a common arguments type.
     */
    void *argv;
} crt0_ctx_t;

/**
 * @warning MUST REMAIN SYNCHRONIZED with libpip-riot and FAE format definitions.
 */
typedef struct xipfs_crt0_ctx_data_s {
    /*
     * Start address of the file in NVM,
     * which is the text segment of the xipfs file.
     */
    void *file_base;
    /*
     * true if the context is executed in user mode with configured MPU regions,
     * false otherwise
     */
    unsigned char is_safe_call;
    /*
     * Table of function pointers for functions used by stdriot.
     */
    void **syscall_table;
    /*
     * Number of arguments passed to the relocatable binary.
     */
    int argc;
    /*
     * Arguments passed to the relocatable binary.
     */
    char *argv[XIPFS_EXEC_ARGC_MAX];
    /*
     * RIOT's Global Offset Table
     */
    const void *former_got;
    /*
     * Relocatable binary's current got
     */
    const void *current_got;

} xipfs_crt0_ctx_data_t;

typedef struct memories_context_s {
    /**
     * Reserved memory space in RAM for the free RAM to be used
     * by the relocatable binary
     */
    //char ram_start[XIPFS_FREE_RAM_SIZE-1] __attribute__((aligned(XIPFS_FREE_RAM_SIZE)));
    char ram_start[XIPFS_FREE_RAM_SIZE-1] __attribute__((aligned(4096)));
    /**
     * Last byte of the free RAM
     */
    char ram_end;
    /**
     * Reserved memory space in RAM for the stack to be used by
     * the relocatable binary
     */
    char stkbot[EXEC_STACKSIZE_DEFAULT-4] __attribute__((aligned(EXEC_STACKSIZE_DEFAULT)));
    /**
     * Last word of the stack indicating the top of the stack
     */
    char stktop[4];
} memories_context_t;

#if defined(XIPFS_ENABLE_SAFE_EXEC_SUPPORT)
extern const void *xipfs_shared_api_code_start;
extern const void *xipfs_shared_api_code_end;
#endif

/*
 * Global variables
 */

/**
 * @internal
 *
 * @brief The memories context of a relocatable binary
 */
static memories_context_t memories_context;

/**
 * @internal
 *
 * @brief The crt0 context used to perform exec/safe_exec
 */
static crt0_ctx_t *crt0_context;

/**
 * @internal
 *
 * @brief The stack pointer used to perform exec/safe_exec
 */
static char *stack_top;

#if defined(XIPFS_ENABLE_SAFE_EXEC_SUPPORT)
/**
 * @internal
 * @brief Real syscalls table.
 *
 * In xipfs_safe_exec, we set a table of wrappers into xipfs_crt0_ctx_data.
 * These latter are trampoline functions that trigger a svc.
 *
 * While processing the svc in xipfs_syscall_dispatcher, we need the real original
 * syscalls table to perform the actual code, which is stored here thanks to
 * exec_syscalls_init_safe.
 *
 * @see exec_syscalls_init_safe
 * @see xipfs_syscall_dispatcher
 */
static const void **xipfs_safe_exec_syscalls_table;

/**
 * The mpu region identifier used to protect Text segment
 */
static xipfs_mpu_region_enum_t mpu_region_current_text;

#endif

/**
 * @internal
 *
 * @brief A reference to the stack's state prior to invoking
 * execv(2)
 */
static void *_exec_curr_stack USED;

/**
 * @brief A pointer to a virtual file name
 */
char *xipfs_infos_file = "/.xipfs_infos";

/*
 * Helper functions
 */

/**
 * @internal
 *
 * @brief Local implementation of exit(3) passed to the binary
 * through the syscall table
 *
 * @param status The exit(3) status of the binary is stored in
 * the R0 register
 */
/* TODO: Move this function into board-specific functions */
void NAKED
xipfs_exec_exit(int status)
{
#if XIPFS_HAS_ARM_EXEC
    __asm__ volatile
    (
        " mov r0, %0\n"
        " ldr r4, =_exec_curr_stack \n"
        " ldr sp, [r4]              \n"
        " pop {r4, pc}              \n"
        ::"r"(status):"r0"
    );
#else /* XIPFS_HAS_ARM_EXEC */

    /* On workstation, we don't need to execute any file
     * but we have to silence compiler warnings.
     */
#ifdef XIPFS_WORKSTATION
    (void)status;
#else
#error "No implementation for xipfs_exec_exit"
#endif

#endif /* XIPFS_HAS_ARM_EXEC */
}

/**
 * @internal
 *
 * @brief Starts the execution of the binary in the current RIOT
 * thread
 */
/* TODO: Move this function into board-specific functions */
static void NAKED
xipfs_exec_enter(void *crt0_ctx UNUSED,
                 void *entry_point UNUSED,
                 void *stack_top UNUSED)
{
#if XIPFS_HAS_ARM_EXEC
    __asm__ volatile
    (
        " push {r4, lr}             \n"
        " ldr r4, =_exec_curr_stack \n"
        " str sp, [r4]              \n"
        " mov sp, r2                \n"
        " blx r1                    \n"
    );
#else /* XIPFS_HAS_ARM_EXEC */

#if defined(XIPFS_WORKSTATION)
    (void)crt0_ctx;
    (void)entry_point;
    (void)stack_top;
#else
#error "No implementation for xipfs_exec_enter"
#endif

#endif /* XIPFS_HAS_ARM_EXEC */
}

/**
 * @internal
 *
 * @brief Converts an address into a thumb address
 *
 * @param addr The address to convert
 *
 * @return The converted address
 */
#if XIPFS_HAS_ARM_EXEC
static inline void *thumb(void *addr)
{
    return (void *)((uintptr_t)addr | 1);
}
#endif /* XIPFS_HAS_ARM_EXEC */

/**
 * @internal
 *
 * @brief Clean up the context of the relocatable binary
 *
 * @param exec_ctx The address of the context to clean up
 */
static inline void
exec_cleanup(void)
{
    (void)memset(&memories_context, 0, sizeof(memories_context));
    crt0_context = NULL;
    stack_top = NULL;
#if defined(XIPFS_ENABLE_SAFE_EXEC_SUPPORT)
    xipfs_safe_exec_syscalls_table = NULL;
#endif
}

/**
 * @internal
 *
 * @brief Fills the CR0 and xipfs_crt0_ctx_data structures
 *
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 */
static inline void
exec_crt0_init(xipfs_file_t *filp)
{
    xipfs_crt0_ctx_data_t   *xipfs_crt0_ctx_data;
    size_t size;
    void *end;

    /* Map crt0 context and xipfs_crt0_ctx_data onto the stack */
    crt0_context = (crt0_ctx_t *)(void *)((&(memories_context.stktop[4])) - sizeof(crt0_ctx_t));
    xipfs_crt0_ctx_data = (xipfs_crt0_ctx_data_t *)(void *)(((char *)crt0_context) - sizeof(xipfs_crt0_ctx_data_t));
    stack_top = (char *)xipfs_crt0_ctx_data;

    crt0_context->argv = xipfs_crt0_ctx_data;

    stack_top = (char *)xipfs_crt0_ctx_data;

    crt0_context->bin_base = filp->buf;

    crt0_context->ram_start = memories_context.ram_start;
    crt0_context->ram_end = &memories_context.ram_end;

    size = xipfs_file_get_size_(filp);
    crt0_context->nvm_start = &filp->buf[size];

    end = (char *)filp + filp->reserved;
    crt0_context->nvm_end = end;

    xipfs_crt0_ctx_data->file_base = filp;
#if XIPFS_HAS_ARM_EXEC
    __asm__ volatile (
        "mov %0, sl"
        : "=r"(xipfs_crt0_ctx_data->former_got)
    );
#else /* XIPFS_HAS_ARM_EXEC */

#if defined(XIPFS_WORKSTATION)
    /* On workstation, we do not execute any file, but to prevent from trash value
     * we set the former got to NULL.
     */
    xipfs_crt0_ctx_data->former_got = NULL;
#else
#error "There is no implementation for setting xipfs_crt0_ctx_data->former_got in exec_crt0_init"
#endif

#endif /* XIPFS_HAS_ARM_EXEC */
}

/**
 * @internal
 *
 * @brief Copies argument pointers to the crt0 context
 *
 * @param argv A pointer to a list of pointers to memory regions
 * containing accessible arguments to pass to the binary
 */
static inline void
exec_args_init(char *const argv[])
{
    xipfs_crt0_ctx_data_t *xipfs_crt0_ctx_data = (xipfs_crt0_ctx_data_t *)crt0_context->argv;

    unsigned int argc = 0;
    while (argc < XIPFS_EXEC_ARGC_MAX &&  argv[argc] != NULL) {
        xipfs_crt0_ctx_data->argv[argc] = argv[argc];
        argc++;
    }

    xipfs_crt0_ctx_data->argc = argc;
}

/**
 * @internal
 *
 * @brief Copies arguments to the executable stack.
 *
 * To be able to access executable arguments, these ones are copied into the stack,
 * and then are allowed to be read/written due to stack's MPU region.
 * Please note that this copy starts at stack_top and goes backwards memory-wise.
 *
 * @param argv A pointer to a list of pointers to memory regions
 * containing accessible arguments to pass to the binary
 */
static inline void
exec_args_init_safe(char *const argv[])
{
    xipfs_crt0_ctx_data_t *xipfs_crt0_ctx_data = (xipfs_crt0_ctx_data_t *)crt0_context->argv;
    char *stack_ptr = stack_top;
    size_t arg_length;

    unsigned int argc = 0;
    while (argc < XIPFS_EXEC_ARGC_MAX &&  argv[argc] != NULL) {

        arg_length = strlen(argv[argc]);
        stack_ptr -= arg_length + 1;

        /* Do we have enough space left in the stack to copy the argument ? */
        if (stack_ptr < memories_context.stkbot) {
            stack_top = NULL;
            return;
        }
        memcpy(stack_ptr, argv[argc], arg_length);
        stack_ptr[arg_length] = '\0';

        xipfs_crt0_ctx_data->argv[argc] = stack_ptr;
        argc++;
    }

    xipfs_crt0_ctx_data->argc = argc;

    /* Align the stack to a 4 bytes limit */
    stack_ptr -= ((uintptr_t)stack_ptr) % 4;

    stack_top = stack_ptr;
}

/**
 * @internal
 *
 * @brief Copies syscalls pointers to the executable stack.
 *
 * To prevent from using another MPU region, the syscalls pointers are copied
 * onto the executable stack.
 * Because the latter already has its associated MPU region, it allows
 * the executable to have access to the syscalls table.
 *
 * @param syscalls The syscalls function pointers to copy.
 */
static void **exec_syscalls_copy_to_stack(const void *syscalls[XIPFS_SYSCALL_MAX])
{
    const unsigned int bytesize = sizeof(void *) * XIPFS_SYSCALL_MAX;
    if ( (stack_top - bytesize) < memories_context.stkbot) {
        stack_top = NULL;
        return NULL;
    }

    stack_top -= bytesize;
    memcpy(stack_top, syscalls, bytesize);
    return (void **)(uintptr_t)stack_top;
}

/**
 * @internal
 *
 * @brief Sets the syscalls table in xipfs_crt0_ctx_data.
 *
 * @param syscalls Syscalls table to set.
 *
 * Because both unsafe and safe programs executions share the same CRT0 structure,
 * syscalls pointers must be copied to the executable stack.
 * This location will end up in the non-const pointer of xipfs_crt0_ctx_data_t.
 *
 * @see xipfs_syscall_t.
 * @see exec_init.
 */
static inline void
exec_syscalls_init(const void *syscalls[XIPFS_SYSCALL_MAX])
{
    xipfs_crt0_ctx_data_t *xipfs_crt0_ctx_data = (xipfs_crt0_ctx_data_t *)crt0_context->argv;

    xipfs_crt0_ctx_data->syscall_table = exec_syscalls_copy_to_stack(syscalls);
    xipfs_crt0_ctx_data->is_safe_call  = 0;
}


#if defined(XIPFS_ENABLE_SAFE_EXEC_SUPPORT)
/**
 * @internal
 *
 * @brief Sets the syscalls table in xipfs_safe_exec_syscalls_table and wrappers in xipfs_crt0_ctx_data.
 *
 * Wrappers are trampoline functions triggering syscalls, that will call the actual functions stored into
 * xipfs_safe_exec_syscalls_table.
 * Note that the actual functions pointers are copied onto executable stack to benefit from its MPU region.
 *
 * @param syscalls Syscalls table to set.
 *
 * @see xipfs_syscall_t.
 * @see exec_init_safe.
 */
static inline void
exec_syscalls_init_safe(const void *syscalls[XIPFS_SYSCALL_MAX])
{
    xipfs_crt0_ctx_data_t *xipfs_crt0_ctx_data = (xipfs_crt0_ctx_data_t *)crt0_context->argv;

    xipfs_crt0_ctx_data->syscall_table =
        exec_syscalls_copy_to_stack(xipfs_safe_exec_syscalls_wrappers);
    xipfs_crt0_ctx_data->is_safe_call  = 1;

    xipfs_safe_exec_syscalls_table = syscalls;
}
#endif

/**
 * @internal
 *
 * @brief Execution context initializer.
 *
 * @param filp The file pointer from where to run execution
 * @param argv the execution arguments
 * @param user_syscalls The user syscalls table
 */
static inline void
exec_init(xipfs_file_t *filp,
          char *const argv[],
          const void *syscalls[XIPFS_SYSCALL_MAX])
{
    exec_crt0_init(filp);
    exec_args_init(argv);
    exec_syscalls_init(syscalls);
}

#if defined(XIPFS_ENABLE_SAFE_EXEC_SUPPORT)
/**
 * @internal
 *
 * @brief Execution context initializer.
 *
 * This function will :
 * - map crt0_context onto the stack space,
 * - then copy after the arguments into stack,
 * - and finally set syscalls tables.
 *
 * @param filp The file pointer from where to run execution
 * @param argv the execution arguments
 * @param syscalls The user syscalls table
 *
 */
static inline void
exec_init_safe(xipfs_file_t *filp,
               char *const argv[],
               const void *syscalls[XIPFS_SYSCALL_MAX])
{
    exec_crt0_init(filp);
    exec_args_init_safe(argv);
    if(stack_top == NULL)
        return;

    exec_syscalls_init_safe(syscalls);
}
#endif

/*
 * Extern functions
 */

/**
 * @internal
 *
 * @brief Checks if the character passed as an argument is in
 * the xipfs charset
 *
 * @param c The character to check
 *
 * @return Returns one if the character passed as an argument is
 * in the xipfs charset or a zero otherwise
 */
static int
xipfs_file_path_charset_check(char c)
{
    return (c >= '0' && c <= '9') ||
           (c >= 'A' && c <= 'Z') ||
           (c >= 'a' && c <= 'z') ||
            c == '/' || c == '.'  ||
            c == '-' || c == '_';
}

/**
 * @pre path must be a pointer that references a path which is
 * accessible, null-terminated, starts with a slash, normalized,
 * and shorter than XIPFS_PATH_MAX
 *
 * @brief Checks if the path passed as an argument is a valid
 * xipfs path
 *
 * @param path The path to check
 *
 * @return Returns zero if the path passed an an argument is a
 * valid xipfs path or a negative value otherwise
 */
int
xipfs_file_path_check(const char *path)
{
    size_t i;

    if (path == NULL) {
        xipfs_errno = XIPFS_ENULLP;
        return -1;
    }
    if (path[0] == '\0') {
        xipfs_errno = XIPFS_EEMPTY;
        return -1;
    }
    for (i = 0; i < XIPFS_PATH_MAX && path[i] != '\0'; i++) {
        if (xipfs_file_path_charset_check(path[i]) == 0) {
            xipfs_errno = XIPFS_EINVAL;
            return -1;
        }
    }
    if (path[i] != '\0') {
        xipfs_errno = XIPFS_ENULTER;
        return -1;
    }

    return 0;
}

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @brief Checks if the xipfs file structure passed as an
 * argument is a valid one
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp The xipfs file structure to check
 *
 * @return Returns zero if the xipfs file structure passed as an
 * argument is a valid one or a negative value otherwise
 */
int
xipfs_file_filp_check(const xipfs_mount_t *mountp, const xipfs_file_t *filp)
{
    xipfs_memory_offset_t filp_off;

    if (filp == NULL) {
        xipfs_errno = XIPFS_ENULLF;
        return -1;
    }
    if (xipfs_flash_page_aligned(filp) < 0) {
        xipfs_errno = XIPFS_EALIGN;
        return -1;
    }
    if (xipfs_flash_in(filp) < 0) {
        xipfs_errno = XIPFS_EOUTNVM;
        return -1;
    }
    if (filp->next == XIPFS_MEMORY_OFFSET_ERASED) {
        xipfs_errno = XIPFS_ENULLF;
        return -1;
    }
    filp_off = xipfs_pointer_to_offset(mountp, filp);
    if (filp->next != filp_off) {
        xipfs_file_t *nextp = xipfs_offset_to_pointer(mountp, filp->next);

        if (xipfs_flash_page_aligned(nextp) == 0) {
            xipfs_errno = XIPFS_EALIGN;
            return -1;
        }
        if (xipfs_flash_in(nextp) == 0) {
            xipfs_errno = XIPFS_EOUTNVM;
            return -1;
        }
        if ((uintptr_t)filp >= (uintptr_t)nextp) {
            xipfs_errno = XIPFS_ELINK;
            return -1;
        }
        if ((uintptr_t)filp + filp->reserved != (uintptr_t)nextp) {
            xipfs_errno = XIPFS_ELINK;
            return -1;
        }
        if (   (sizeof(*filp) > XIPFS_FILE_POSITION_MAX_AS_SIZE_T)
            || ((size_t)filp->reserved < sizeof(*filp)) ) {
            xipfs_errno = XIPFS_EINVAL;
            return -1;
        }
    }
    if (filp->reserved < XIPFS_FILE_POSITION_MIN) {
        xipfs_errno = XIPFS_EINVAL;
        return -1;
    }
    if (xipfs_file_path_check(filp->path) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    if (filp->exec != 0 && filp->exec != 1) {
        xipfs_errno = XIPFS_EPERM;
        return -1;
    }

    return 0;
}

/**
 * @pre filp must be a pointer to an accessible and valid
 * file structure
 *
 * @brief Retrieves the maximum possible position of a file
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp A pointer to a memory region containing a
 * file structure
 *
 * @return Returns the maximum possible position of the file or
 * a negative value otherwise
 */
xipfs_file_position_t
xipfs_file_get_max_pos(const xipfs_mount_t *mountp, const xipfs_file_t *filp)
{
    xipfs_file_position_t max_pos;

    assert(filp != NULL);

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    max_pos = filp->reserved - (xipfs_file_position_t)sizeof(*filp);

    return max_pos;
}

/**
 * @pre vfs_filp must be a pointer to an accessible and valid
 * file structure
 *
 * @brief Retrieves the reserved size of a file
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp A pointer to a memory region containing a
 * file structure
 *
 * @return Returns the reserved size of the file or a negative
 * value otherwise
 */
xipfs_file_position_t
xipfs_file_get_reserved(const xipfs_mount_t *mountp, const xipfs_file_t *filp)
{
    xipfs_file_position_t reserved;

    assert(filp != NULL);

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    reserved = filp->reserved;

    return reserved;
}

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @brief Removes a file from the file system
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @return Returns zero if the function succeeds or a negative
 * value otherwise
 */
int
xipfs_file_erase(const xipfs_mount_t *mountp, xipfs_file_t *filp)
{
    unsigned start, number, i;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    start = xipfs_nvm_page(filp);
    number = (unsigned)filp->reserved / XIPFS_NVM_PAGE_SIZE;

    for (i = 0; i < number; i++) {
        if (xipfs_flash_erase_page(start + i) < 0) {
            /* xipfs_errno was set */
            return -1;
        }
    }

    return 0;
}

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @brief Retrieves the current file size from the list of
 * previous sizes
 *
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @return Returns the current file size or a negative value
 * otherwise
 */
xipfs_file_position_t
xipfs_file_get_size_(const xipfs_file_t *filp)
{
    size_t i = 1;
    xipfs_file_position_t size, last_size;

    if (xipfs_buffer_read_32((unsigned *)&size, &(filp->size[0])) < 0) {
        // xipfs_errno has been set.
        return -1;
    }

    if (size == (xipfs_file_position_t)XIPFS_FLASH_ERASE_STATE) {
        /* file size not in flash yet */
        return 0;
    }

    // Find last occupied slot.
    last_size = size;
    while (i < XIPFS_FILESIZE_SLOT_MAX) {
        if (xipfs_buffer_read_32((unsigned *)&size, &(filp->size[i])) < 0) {
            // xipfs_errno has been set.
            return -1;
        }

        if (size == (xipfs_file_position_t)XIPFS_FLASH_ERASE_STATE) {
            return last_size;
        }

        i++;
        last_size = size;
    }

    // We've browsed all the slots array. Return the last read size.
    return last_size;
}

/**
 * @pre vfs_filp must be a pointer to an accessible and valid
 * xipfs file structure
 *
 * @brief Wrapper to the xipfs_file_get_size_ function that
 * checks the validity of the xipfs file strucutre
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @return Returns the current file size or a negative value
 * otherwise
 */
xipfs_file_position_t
xipfs_file_get_size(const xipfs_mount_t *mountp, const xipfs_file_t *filp)
{
    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    return xipfs_file_get_size_(filp);
}

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @brief Sets the new file size to the list of previous sizes
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @param size The size to set to the file
 *
 * @return Returns zero if the function succeed or a negative
 * value otherwise
 */
int
xipfs_file_set_size(const xipfs_mount_t *mountp, xipfs_file_t *filp, xipfs_file_position_t size)
{
    size_t i = 0;
    xipfs_file_position_t flash_value;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    if (size > filp->reserved) {
        xipfs_errno = XIPFS_EOUTNVM;
        return -1;
    }

    if (size < XIPFS_FILE_POSITION_MIN) {
        xipfs_errno = XIPFS_EINVALIDSIZE;
        return -1;
    }

    // Find the first free size slot.
    while (i < XIPFS_FILESIZE_SLOT_MAX) {
        if (xipfs_buffer_read_32((unsigned int *)&flash_value, &(filp->size[i])) < 0) {
            // xipfs_errno has been set.
            return -1;
        }
        if (flash_value == (xipfs_file_position_t)XIPFS_FLASH_ERASE_STATE) {
            goto write_size;
        }
        i++;
    }

    // No free slot, reinit the slots array, except from the first slot.
    i = 1;
    while (i < XIPFS_FILESIZE_SLOT_MAX) {
        if (xipfs_buffer_write_32(&(filp->size[i]), (unsigned)XIPFS_FLASH_ERASE_STATE) < 0) {
            // xipfs_errno has been set.
            return -1;
        }
        i++;
    }

    // restart at slot 0.
    i = 0;

write_size :
    if (xipfs_buffer_write_32(&(filp->size[i]), (unsigned)size) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    if (xipfs_buffer_flush() < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    return 0;
}

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @pre path must be a pointer that references a path which is
 * accessible, null-terminated, starts with a slash, normalized,
 * and shorter than XIPFS_PATH_MAX
 *
 * @brief Changes the path of an xipfs file
 *
 * @param mountp The xipfs mount point structure hosting filp.
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @param to_path The new path of the file
 *
 * @return Returns zero if the function succeed or a negative
 * value otherwise
 */
int
xipfs_file_rename(const xipfs_mount_t *mountp, xipfs_file_t *filp, const char *to_path)
{
    size_t len;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    if (xipfs_file_path_check(to_path) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    len = strlen(to_path) + 1;

    if (xipfs_buffer_write(filp->path, to_path, len) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    if (xipfs_buffer_flush() < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    return 0;
}

/**
 * @pre vfs_filp must be a pointer to an accessible and valid
 * file structure
 *
 * @brief Reads a byte from the current position of the open
 * file
 *
 * @param mountp The xipfs mount point structure hosting filp.
 *
 * @param filp A pointer to a memory region containing an
 * accessible and open file structure
 *
 * @param pos An offset from the beginning of the file.
 *
 * @param byte A pointer to a memory region where to store the
 * read byte
 *
 * @return Returns zero if the function succeed or a negative
 * value otherwise
 */
int
xipfs_file_read_8(const xipfs_mount_t *mountp, xipfs_file_t *filp,
                  xipfs_file_position_t pos, char *byte)
{
    xipfs_file_position_t pos_max;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    if ((pos_max = xipfs_file_get_max_pos(mountp, filp)) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    /* Since xipfs_file_position_t is defined as an int32_t, we must
     * verify that the value is non-negative. */
    if (pos < XIPFS_FILE_POSITION_MIN || pos > pos_max) {
        xipfs_errno = XIPFS_EMAXOFF;
        return -1;
    }
    if (xipfs_buffer_read_8(byte, &filp->buf[pos]) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    return 0;
}

/**
 * @pre vfs_filp must be a pointer to an accessible and valid
 * file structure
 *
 * @brief Writes a byte from to the current position of the open
 * file
 *
 * @param mountp The xipfs mount point structure hosting filp.
 *
 * @param filp A pointer to a memory region containing an
 * accessible and open file structure
 *
 * @param pos An offset from the beginning of the file.
 *
 * @param byte The byte to write to the current position of the
 * open file
 *
 * @return Returns zero if the function succeed or a negative
 * value otherwise
 */
int
xipfs_file_write_8(const xipfs_mount_t *mountp, xipfs_file_t *filp,
                   xipfs_file_position_t pos, char byte)
{
    xipfs_file_position_t pos_max;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    if ((pos_max = xipfs_file_get_max_pos(mountp, filp)) < 0) {
        /* xipfs_errno was set */
        return -1;
    }
    /* Since xipfs_file_position_t is defined as an int32_t, we must
     * verify that the value is non-negative. */
    if (pos < XIPFS_FILE_POSITION_MIN || pos > pos_max) {
        xipfs_errno = XIPFS_EMAXOFF;
        return -1;
    }
    if (xipfs_buffer_write_8(&filp->buf[pos], byte) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    return 0;
}

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @brief Executes a binary in the current RIOT thread
 *
 * @param mountp The xipfs mount point structure hosting filp.
 *
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @param argv A pointer to a list of pointers to memory regions
 * containing accessible arguments to pass to the binary
 *
 * @param user_syscalls A pointer to a list of pointers defining a syscalls
 * table as stated by xipfs_syscall_t.
 *
 * @return Returns zero if the function succeed or a negative
 * value otherwise
 */
int
xipfs_file_exec(const xipfs_mount_t *mountp, xipfs_file_t *filp,
                char *const argv[], const void *syscalls[XIPFS_SYSCALL_MAX])
{
#if XIPFS_HAS_ARM_EXEC
    void *entry_point;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    exec_cleanup();
    exec_init(filp, argv, syscalls);
    if (stack_top == NULL) {
        return -1;
    }
    entry_point = thumb(&filp->buf[0]);
    xipfs_exec_enter(crt0_context, entry_point, stack_top);

    int status;
    __asm__ volatile(
        " mov %0, r0  \n"
        : "=r"(status)
    );

    return status;
#else /* XIPFS_HAS_ARM_EXEC */

#if defined(XIPFS_WORKSTATION)
    /* On workstation, there is no file execution */
    (void)mountp;
    (void)filp;
    (void)argv;
    (void)syscalls;
    xipfs_errno = XIPFS_EINVAL;
    return -1;
#else
#error "No implementation for xipfs_file_exec"
#endif

#endif /* XIPFS_HAS_ARM_EXEC */
}

#ifdef XIPFS_ENABLE_SAFE_EXEC_SUPPORT

/**
 * @internal
 *
 * @pre Should be only called by xipfs_file_safe_exec
 *
 * @brief disables all xipfs regions, restores mpu state and interruptions.
 *
 * @param mpu_was_enabled Mpu state to restore or not.
 */
static void on_mpu_setting_error(bool mpu_was_enabled) {
    for (int i = XIPFS_MPU_REGION_ENUM_FIRST; i <= XIPFS_MPU_REGION_ENUM_LAST; ++i)
        (void)mpu_configure((uint_fast8_t)i, 0, 0);

    if (mpu_was_enabled)
        (void)mpu_enable();

    __DSB();
    __ISB();
    __enable_irq();
}

/**
 * @internal
 *
 * @brief Calls an SVC to switch from thread mode to handler mode
 * and be able to switch to user thread mode safely
 *
 * @param crt0 A pointer to the crt0 context to execute the binary
 *
 * @param entrypoint A pointer to the entrypoint of the binary
 *
 * @param stack A pointer to the top of the binary's stack
 */
static void NAKED xipfs_file_safe_exec_svc(crt0_ctx_t *crt0 UNUSED, void *entrypoint UNUSED, void *stack UNUSED) {
    /**
     * The arguments are passed to the SVC call through r0, r1, and r2
     */
    __asm__ volatile(
        " push   {lr}                        \n"
        " ldr    r4, =_exec_curr_stack       \n" // get the current stack
        " str    sp, [r4]                    \n" // save current SP
        " svc #" STR(XIPFS_ENTER_SVC_NUMBER) " \n");
}

/**
 * @internal
 * @brief Runtime MPU check.
 *
 * Attention :
 * - We implement only ARMv7-M MPU code path; then we need to disable it
 *   when compiling for ARMv8-M model.
 * - When XIPFS is compiled for RIOT, there are targets with an ARMv8-M MPU.
 * - There is NO fine-grained feature filter that can be used to prevent from code compilation
 *   or tests running.
 * - In RIOT, we need to compile xipfs package and tests for these platforms, and
 *   failing at runtime instead of compile-time, as done formerly.
 * - Thus, xipfs_check_mpu is responsible for runtime cancelling according to compile-time
 *   preprocessor symbols.
*/
static int xipfs_check_mpu(void) {
#if (defined(__ARM_ARCH_8M_MAIN__) || defined(__ARM_ARCH_8M_BASE__))
    xipfs_errno = XIPFS_ENOMPUSUPPORT;
    return -1;
#else
    return 0;
#endif // (defined(__ARM_ARCH_8M_MAIN__) || defined(__ARM_ARCH_8M_BASE__))
}

#endif /* XIPFS_ENABLE_SAFE_EXEC_SUPPORT */

/**
 * @pre filp must be a pointer to an accessible and valid xipfs
 * file structure
 *
 * @brief Executes a binary in user mode protected by the MPU
 *
 * @param mountp The xipfs mount point structure hosting filp.
 *
 * @param filp A pointer to a memory region containing an
 * accessible xipfs file structure
 *
 * @param argv A pointer to a list of pointers to memory regions
 * containing accessible arguments to pass to the binary
 *
 * @param syscalls A pointer to a list of pointers defining a syscalls
 * table as stated by xipfs_syscall_t.
 *
 * @return Returns zero if the function succeed or a negative
 * value otherwise
 */
int xipfs_file_safe_exec(const xipfs_mount_t *mountp, xipfs_file_t *filp,
                         char *const argv[], const void *syscalls[XIPFS_SYSCALL_MAX])
{
#if defined(XIPFS_ENABLE_SAFE_EXEC_SUPPORT)
    void *exec_entry_point;
    int status = -1;
    bool mpu_was_enabled;

    if (xipfs_file_filp_check(mountp, filp) < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    /* Attention:
     * We must fail at runtime after xipfs_file_filp_check,
     * so the tests in RIOT will succeed even on ARMv8-M boards.
     * There is no fine-grained feature to avoid to run tests for them.
     * Then, we must cancel xipfs_file_safe_exec here.
     * @see xipfs_check_mpu
     */
    if (xipfs_check_mpu() < 0) {
        /* xipfs_errno was set */
        return -1;
    }

    /* Initialize crt0, xipfs_crt0_ctx_data */
    exec_cleanup();
    exec_init_safe(filp, argv, syscalls);
    if (stack_top == NULL) {
        return -1;
    }

    /* Check memories_context members, filp alignments and shared API start address. */
    if (!(
              ((uint32_t)memories_context.stkbot % EXEC_STACKSIZE_DEFAULT == 0)
           && ((uint32_t)memories_context.ram_start % 4096 == 0)
           && ((uint32_t)filp % XIPFS_NVM_PAGE_SIZE == 0)
           && (((uint32_t)xipfs_shared_api_code_start & ~1) % XIPFS_SHARED_API_CODE_ALIGNMENT == 0)
         )) {
        xipfs_errno = XIPFS_EALIGN;
        return -1;
    }

    const uint32_t xipfs_shared_api_code_size = ((uintptr_t)xipfs_shared_api_code_end) - ((uintptr_t)xipfs_shared_api_code_start);
    if (xipfs_shared_api_code_size != XIPFS_SHARED_API_CODE_SIZE) {
        xipfs_errno = XIPFS_ESHAREDAPISIZE;
        return -1;
    }

    exec_entry_point = thumb(&filp->buf[0]);

    /* IRQ and MPU off */
    __disable_irq();

    if (mpu_enabled()) {
        mpu_was_enabled = true;

        if (mpu_disable() < 0) {
            __enable_irq();
            xipfs_errno = XIPFS_EDISABLEMPU;
            return -1;
        }
    } else
        mpu_was_enabled = false;

    /* Set MPU regions for text, data and stack */

    /*
     * Regarding to the TEXT segment, we use 2 MPU regions
     * that are set alternatively according to MPU faults.
     * This scheme allows to handle instructions which would be
     * astride the boundary of 2 memory regions.
     */
    mpu_region_current_text = XIPFS_MPU_REGION_ENUM_TEXT;
    if (xipfs_mpu_configure_region(
            mpu_region_current_text,
            filp, XIPFS_NVM_PAGE_SIZE,
            XIPFS_MPU_REGION_EXC_OK, XIPFS_MPU_REGION_AP_RO_RO) < 0) {

        on_mpu_setting_error(mpu_was_enabled);
        xipfs_errno = XIPFS_ETEXTREGION;
        return -1;
    }

    /*
     * Set MPU region for shared api code.
     */
    uintptr_t shared_api_code_start = ((uintptr_t)xipfs_shared_api_code_start) & ~1;
    if (xipfs_mpu_configure_region(
            XIPFS_MPU_REGION_ENUM_SHARED_API,
            (void *)shared_api_code_start, XIPFS_SHARED_API_CODE_SIZE,
            XIPFS_MPU_REGION_EXC_OK, XIPFS_MPU_REGION_AP_RO_RO) < 0) {

        on_mpu_setting_error(mpu_was_enabled);
        xipfs_errno = XIPFS_ESHAREDAPIREGION;
        return -1;
    }

    /*
     * For the DATA segment, we can take advantage of the data size,
     * fixed to 12 KB while aligning the ram to 4 KB boundaries.
     * Within these conditions, it is possible to set 2 regions once
     * for all, with no dynamic region assignments.
     *
     * When the ram is aligned to a 8 Kb boundary :
     * - Set the first region A to {ram start, 8 KB size};
     * - Set the second region B to {ram start + 8 KB, 4 KB size}.
     *
     * +--------+----+
     * |    A   |  B |
     * +--------+----+
     * |        |    |
     * |        |    .-- Ram start + 12 KB
     * |        .------- Ram start + 8 KB
     * .---------------- Ram starts at a 8KB boundary
     *
     * When the ram is aligned to a (8 + 4) KB boundary (which is a 4 KB boundary) :
     * - Set the first region A to {ram start, 4 KB size};
     * - Set the second region B to {ram start + 4 KB, 8 KB size}.
     * +----+--------+
     * |  A |    B   |
     * +----+--------+
     * |    |        |
     * |    |        .-- Ram start + 12 KB
     * |    .----------- Ram start + 4 KB
     * .---------------- Ram starts at a 4 KB boundary, while not being a 8 KB one.
     *
     * These two cases cover up the whole 12 KB of ram, with no need for dynamic regions setting.
     */
    /* Are we on a 8 KB boundary ? */
    if ( ((((uint32_t)memories_context.ram_start) >> 12) & 1) == 0 ) {
        if (xipfs_mpu_configure_region(
                XIPFS_MPU_REGION_ENUM_DATA,
                memories_context.ram_start, 8192,
                XIPFS_MPU_REGION_EXC_NO, XIPFS_MPU_REGION_AP_RW_RW) < 0) {

            on_mpu_setting_error(mpu_was_enabled);

            xipfs_errno = XIPFS_EDATAREGION;
            return -1;
        }

        if (xipfs_mpu_configure_region(
                XIPFS_MPU_REGION_ENUM_EXTRA_DATA,
                memories_context.ram_start + 8192, 4096,
                XIPFS_MPU_REGION_EXC_NO, XIPFS_MPU_REGION_AP_RW_RW) < 0) {

            on_mpu_setting_error(mpu_was_enabled);

            xipfs_errno = XIPFS_EDATAREGION;
            return -1;
        }

    } else {
        if (xipfs_mpu_configure_region(
                XIPFS_MPU_REGION_ENUM_DATA,
                memories_context.ram_start, 4096,
                XIPFS_MPU_REGION_EXC_NO, XIPFS_MPU_REGION_AP_RW_RW) < 0) {

            on_mpu_setting_error(mpu_was_enabled);

            xipfs_errno = XIPFS_EDATAREGION;
            return -1;
        }

        if (xipfs_mpu_configure_region(
                XIPFS_MPU_REGION_ENUM_EXTRA_DATA,
                memories_context.ram_start + 4096, 8192,
                XIPFS_MPU_REGION_EXC_NO, XIPFS_MPU_REGION_AP_RW_RW) < 0) {

            on_mpu_setting_error(mpu_was_enabled);

            xipfs_errno = XIPFS_EDATAREGION;
            return -1;
        }
    }

    /*
     * At last, STACK segment is merely handled by a single MPU region,
     * without any dynamic modification.
     */
    if (xipfs_mpu_configure_region(
            XIPFS_MPU_REGION_ENUM_STACK,
            memories_context.stkbot, EXEC_STACKSIZE_DEFAULT,
            XIPFS_MPU_REGION_EXC_NO, XIPFS_MPU_REGION_AP_RW_RW) < 0) {

        on_mpu_setting_error(mpu_was_enabled);

        xipfs_errno = XIPFS_ESTACKREGION;
        return -1;
    }


    /* Enable MPU if it is not already */
    if (mpu_enable() != 0) {
        on_mpu_setting_error(false);
        xipfs_errno = XIPFS_EENABLEMPU;
        return -1;
    }

    __DSB();
    __ISB();
    __enable_irq();

    __asm__ volatile(
        " mrs r0, msp           \n" // save main stack pointer
        " push {r0, r4-r11, lr} \n" // save registers
    );

    xipfs_file_safe_exec_svc(crt0_context, exec_entry_point, stack_top);

    __asm__ volatile(
        " pop {r1, r4-r11, lr} \n" // restore registers
        " msr msp, r1          \n" // restore main stack pointer
        " mov %0, r0           \n" // retrieve exec status
        : "=r"(status)
    );

    __disable_irq();

    /* Disable MPU regions */
    if (mpu_disable() != 0) {
        xipfs_errno = XIPFS_EDISABLEMPU;
        __enable_irq();
        return -1;
    }

    /*
     * Attention :
     * - We need these lines of code to disable MPU regions that have been set.
     * - We cannot fail to compile for ARMv8-M targets in RIOT, for both XIPFS package and tests.
     * - xipfs_check_mpu is responsible to cancel this code path before these lines at runtime
     * @see xipfs_check_mpu
     */
#if (!defined(__ARM_ARCH_8M_MAIN__) && !defined(__ARM_ARCH_8M_BASE__))
    for (xipfs_mpu_region_enum_t i = XIPFS_MPU_REGION_ENUM_FIRST;
         i <= XIPFS_MPU_REGION_ENUM_LAST; ++i) {
        MPU->RNR = i;
        MPU->RASR &= ~MPU_RASR_ENABLE_Msk;
    }
#endif

    /* Restore MPU if it was enabled before calling this function */
    if (mpu_was_enabled && (mpu_enable() != 0)) {
        xipfs_errno = XIPFS_EENABLEMPU;
        __enable_irq();
        return -1;
    }

    __DSB();
    __ISB();
    __enable_irq();

    return status;
#else /* XIPFS_ENABLE_SAFE_EXEC_SUPPORT */
    (void)mountp;
    (void)filp;
    (void)argv;
    (void)syscalls;
    xipfs_errno = XIPFS_ENOSAFESUPPORT;
    return -1;
#endif /* XIPFS_ENABLE_SAFE_EXEC_SUPPORT */
}

#ifdef XIPFS_ENABLE_SAFE_EXEC_SUPPORT

/**
 * @internal
 *
 * @pre control param should be at least 2 because SPSEL bit of the control register should be 1,
 * it means that we should always return from the exception with the psp stack
 *
 * @pre we must be in handler mode to use the exec return mechanism,
 * otherwise an hard fault exception will occur
 *
 * @brief Switch to the context specified with the exception frame
 * stored in the last 32 bytes of the stack parameter and restore the former isr stack start.
 * It uses the arm exec return mechanism to switch safely between user / privileged mode
 *
 * @param stack A pointer to the stack to use after the context switch
 *
 * @param control The flags of the control register to specify if we return in user or privileged mode
 *
 * @param isr_stack_start A pointer to the exception stack top, we must restore it because we never
 * return from the exception
 */
static void NAKED xipfs_switch_context(void *stack UNUSED,
                                       control_register_mode_t control UNUSED,
                                       void *isr_stack_top UNUSED)
{
    __asm__ volatile(
        "cpsid i                                      \n" /* disable interrupts */
        /* Switch to thread mode with psp stack */
        "msr psp, r0                                  \n" /* set psp to begin of stack frame */
        "msr msp, r2                                  \n" /* restore isr stack to end because we never return from the interrupt */
        "msr control, r1                              \n" /* set the control register to control arg */
        "isb                                          \n"
        "ldr r0, =" STR(EXC_RETURN_THREAD_MODE_PSP) " \n" /* exec return to thread mode using psp */
        "cpsie i                                      \n" /* enable interrupts */
        "bx r0                                        \n" /* jump to exec return to thread mode with psp */
    );
}

/**
 * @internal
 *
 * @brief Initialize an exception stack frame by setting all members to zero
 * except from xpsr which is set to thumb mode for switching
 *
 * @param frame A pointer to the exception stack frame used to switch context
 */
static void init_isr_stack_frame(isr_stack_frame_t *frame)
{
    memset(frame, 0, 28);
    frame->xpsr = XPSR_THUMB_MODE;
}

/**
 * Provided by OS host.
 */
extern void *thread_isr_stack_end(void);

void xipfs_safe_exec_enter(void *crt0_context,
                           void *entrypoint,
                           void *stack)
{
    uint32_t *stack_ptr = (uint32_t *)stack;
    stack_ptr -= 8;

    isr_stack_frame_t *frame = (isr_stack_frame_t *)stack_ptr;
    init_isr_stack_frame(frame);
    frame->r0 = (uint32_t)crt0_context;
    frame->pc = (uint32_t)entrypoint;

    void *isr_stack_top = thread_isr_stack_end();
    xipfs_switch_context(stack_ptr, CTRL_USER_PSP, isr_stack_top);
}

/**
 * @internal
 *
 * @pre we must be in handler mode to use the function, otherwise an hard fault
 * will occur on context switch
 *
 * @brief Prepare the exception stack frame to switch back from user mode to
 * privileged mode and exit safely
 *
 * @param status The return status of the safe call
 */
void xipfs_safe_exec_exit(int status) {
    uint32_t *current_stack_ptr = (uint32_t *)_exec_curr_stack;
    uint32_t return_address = *current_stack_ptr;
    current_stack_ptr -= 7; // 7 * 4 = 28, not 32 bytes because we deallocate the return address of 4 bytes

    isr_stack_frame_t *frame = (isr_stack_frame_t *)current_stack_ptr;
    init_isr_stack_frame(frame);
    frame->pc = return_address;
    frame->r0 = status;

    void *isr_stack_top = thread_isr_stack_end();
    xipfs_switch_context(current_stack_ptr, CTRL_PRIV_PSP, isr_stack_top);
}

/**
 * @internal
 *
 * @brief Check if a value is within a specified range
 *
 * @param value The value to check
 *
 * @param begin The beginning of the range
 *
 * @param end The end of the range
 *
 * @return True if the address is withing the specified range, false otherwise
 */
static bool is_value_in_range(uint32_t value, uint32_t begin, uint32_t end)
{
    return value >= begin && value <= end;
}

int xipfs_mem_manage_handler(void *isr_frame_ptr, uint32_t mmfar, uint32_t cfsr)
{
    isr_stack_frame_t *frame = (isr_stack_frame_t *)isr_frame_ptr;
    uint32_t fault_addr = cfsr & SCB_CFSR_MMARVALID_Msk ? mmfar : frame->pc;

    __disable_irq();
    if (mpu_disable() != 0) {
        __enable_irq();
        return -1;
    }

    /* Check if the stack frame is in user stack */
    if (is_value_in_range((uint32_t)isr_frame_ptr,
                          (uint32_t)memories_context.stkbot,
                          (uint32_t)memories_context.stktop + 4) == false) {
        (void)mpu_enable();
        __enable_irq();
        return -2;
    }

    /* Is this a text portion that is faulting ? */
    xipfs_crt0_ctx_data_t *xipfs_crt0_ctx_data = (xipfs_crt0_ctx_data_t *)crt0_context->argv;
    if (is_value_in_range(  fault_addr,
                            (uint32_t)xipfs_crt0_ctx_data->file_base,
                            (uint32_t)crt0_context->nvm_end) == false) {
        printf("Illegal memory access detected at 0x%lx.\n", fault_addr);
        (void)mpu_enable();
        __enable_irq();

        SCB->CFSR = SCB_CFSR_MEMFAULTSR_Msk; /* write-1-to-clear */

        xipfs_safe_exec_exit(-1);
        // Should never be reached.
        return -3;
    }

    /* Set a new text region */
    if (mpu_region_current_text == XIPFS_MPU_REGION_ENUM_TEXT)
        mpu_region_current_text = XIPFS_MPU_REGION_ENUM_EXTRA_TEXT;
    else
        mpu_region_current_text = XIPFS_MPU_REGION_ENUM_TEXT;

    /* The region must be aligned with XIPFS_NVM_PAGE_SIZE and must contain fault_addr */
    fault_addr = (fault_addr / XIPFS_NVM_PAGE_SIZE) * XIPFS_NVM_PAGE_SIZE;

    if (xipfs_mpu_configure_region(
            mpu_region_current_text,
            (char *)fault_addr, XIPFS_NVM_PAGE_SIZE,
            XIPFS_MPU_REGION_EXC_OK, XIPFS_MPU_REGION_AP_RO_RO) < 0) {
        (void)mpu_enable();
        __enable_irq();
        return -4;
    }

    SCB->CFSR = SCB_CFSR_MEMFAULTSR_Msk; /* write-1-to-clear */

    (void)mpu_enable();
    __DSB();
    __ISB();
    __enable_irq();

    return 0;
}

/**
 * @internal
 * @remarks This function uses the user syscall table in exec_ctx.
 * That means that functions called here are RIOT's ones, except from
 * XIPFS_SYSCALL_EXIT.
 *
 * @remarks long and ssize_t are 32 bits wide on arm 32bits.
 */
void xipfs_syscall_dispatcher(unsigned int *svc_args)
{
    unsigned int syscall_number = svc_args[0];
    /*uint32_t *caller_stack;
    uint32_t result;*/

    switch (syscall_number) {
    case XIPFS_SYSCALL_EXIT: {
        int ret_status = svc_args[1];
        xipfs_syscall_exit_t f = (xipfs_syscall_exit_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_EXIT];
        f(ret_status);
        break;
    }
    case XIPFS_SYSCALL_VPRINTF: {
        const char *format = (const char *)svc_args[1];
        va_list ap;
        __asm__ volatile
        (
            "mov %0, %1\n"
            : "=r" (ap)
            : "r" (svc_args[2])
            :
        );
        xipfs_syscall_vprintf_t f = (xipfs_syscall_vprintf_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VPRINTF];
        svc_args[0] = (unsigned int)f(format, ap);
        break;
    }
    case XIPFS_SYSCALL_GET_TEMP: {
        xipfs_syscall_get_temp_t f = (xipfs_syscall_get_temp_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_GET_TEMP];
        svc_args[0] = (unsigned int)f();
        break;
    }
    case XIPFS_SYSCALL_ISPRINT: {
        int character = (int)svc_args[1];
        xipfs_syscall_isprint_t f = (xipfs_syscall_isprint_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_ISPRINT];
        svc_args[0] = (unsigned int)f(character);
        break;
    }
    case XIPFS_SYSCALL_STRTOL: {
        const char *str = (const char *)svc_args[1];
        char **endptr = (char **)svc_args[2];
        int base = (int)svc_args[3];
        xipfs_syscall_strtol_t f = (xipfs_syscall_strtol_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_STRTOL];
        svc_args[0] = (unsigned int)f(str, endptr, base);
        break;
    }
    case XIPFS_SYSCALL_GET_LED: {
        int pos = (int)svc_args[1];
        xipfs_syscall_get_led_t f = (xipfs_syscall_get_led_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_GET_LED];
        svc_args[0] = (unsigned int)f(pos);
        break;
    }
    case XIPFS_SYSCALL_SET_LED: {
        int pos = (int)svc_args[1];
        int val = (int)svc_args[2];
        xipfs_syscall_set_led_t f = (xipfs_syscall_set_led_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_SET_LED];
        svc_args[0] = (unsigned int)f(pos, val);
        break;
    }
    case XIPFS_SYSCALL_COPY_FILE: {
        const char *name = (const char *)svc_args[1];
        void *buf = (void *)svc_args[2];
        size_t nbyte = (size_t)svc_args[3];
        xipfs_syscall_copy_file_t f = (xipfs_syscall_copy_file_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_COPY_FILE];
        svc_args[0] = (unsigned int)f(name, buf, nbyte);
        break;
    }
    case XIPFS_SYSCALL_GET_FILE_SIZE: {
        const char *name = (const char *)svc_args[1];
        size_t *size = (size_t *)svc_args[2];
        xipfs_syscall_get_file_size_t f = (xipfs_syscall_get_file_size_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_GET_FILE_SIZE];
        svc_args[0] = (unsigned int)f(name, size);
        break;
    }
    case XIPFS_SYSCALL_MEMSET: {
        void *m = (void *)svc_args[1];
        int c = (int)svc_args[2];
        size_t n = (size_t)svc_args[3];
        xipfs_syscall_memset_t f = (xipfs_syscall_memset_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_MEMSET];
        svc_args[0] = (uintptr_t)f(m, c, n);
        break;
    }
    case XIPFS_SYSCALL_MEMCMP: {
        const void *s1 = (const void *)svc_args[1];
        const void *s2 = (const void *)svc_args[2];
        size_t n = (size_t)svc_args[3];
        xipfs_syscall_memcmp_t f = (xipfs_syscall_memcmp_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_MEMCMP];
        svc_args[0] = (int)f(s1, s2, n);
        break;
    }
    case XIPFS_SYSCALL_STRCMP: {
        const char *s1 = (const char *)svc_args[1];
        const char *s2 = (const char *)svc_args[2];
        xipfs_syscall_strcmp_t f = (xipfs_syscall_strcmp_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_STRCMP];
        svc_args[0] = (int)f(s1, s2);
        break;
    }
    case XIPFS_SYSCALL_STRNCMP: {
        const char *s1 = (const char *)svc_args[1];
        const char *s2 = (const char *)svc_args[2];
        size_t n = (size_t)svc_args[3];
        xipfs_syscall_strncmp_t f = (xipfs_syscall_strncmp_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_STRNCMP];
        svc_args[0] = (int)f(s1, s2, n);
        break;
    }
    case XIPFS_SYSCALL_VFS_OPEN: {
        /* typedef int (*xipfs_vfs_open_t)(const char *name, int flags, mode_t mode); */
        const char *name = (const char *)svc_args[1];
        int flags = (int)svc_args[2];
        mode_t mode = (mode_t)svc_args[3];
        xipfs_syscall_vfs_open_t f = (xipfs_syscall_vfs_open_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_OPEN];
        svc_args[0] = (int)f(name, flags, mode);
        break;
    }
    case XIPFS_SYSCALL_VFS_CLOSE: {
        int fd = (int)svc_args[1];
        xipfs_syscall_vfs_close_t f = (xipfs_syscall_vfs_close_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_CLOSE];
        svc_args[0] = (int)f(fd);
        break;
    }
    case XIPFS_SYSCALL_VFS_LSEEK: {
        int fd = (int)svc_args[1];
        off_t off = (off_t)svc_args[2];
        int whence = (int)(svc_args[3]);
        xipfs_syscall_vfs_lseek_t f = (xipfs_syscall_vfs_lseek_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_LSEEK];
        svc_args[0] = (ssize_t)f(fd, off, whence);
        break;
    }
    case XIPFS_SYSCALL_VFS_WRITE: {
        int fd = (int)svc_args[1];
        const void *src = (const void *)svc_args[2];
        size_t count = (size_t)(svc_args[3]);
        xipfs_syscall_vfs_write_t f = (xipfs_syscall_vfs_write_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_WRITE];
        svc_args[0] = (ssize_t)f(fd, src, count);
        break;
    }
    case XIPFS_SYSCALL_VFS_READ: {
        int fd = (int)svc_args[1];
        void *dst = (void *)svc_args[2];
        size_t count = (size_t)(svc_args[3]);
        xipfs_syscall_vfs_read_t f = (xipfs_syscall_vfs_read_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_READ];
        svc_args[0] = (ssize_t)f(fd, dst, count);
        break;
    }
    case XIPFS_SYSCALL_VFS_READLINE: {
        int fd = (int)svc_args[1];
        char *dst = (char *)svc_args[2];
        size_t count = (size_t)(svc_args[3]);
        xipfs_syscall_vfs_readline_t f = (xipfs_syscall_vfs_readline_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_READLINE];
        svc_args[0] = (ssize_t)f(fd, dst, count);
        break;
    }
    case XIPFS_SYSCALL_VFS_STAT: {
        const char *name = (const char *)svc_args[1];
        struct stat *stats = (struct stat *)svc_args[2];
        xipfs_syscall_vfs_stat_t f = (xipfs_syscall_vfs_stat_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_STAT];
        svc_args[0] = (int)f(name, stats);
        break;
    }
    case XIPFS_SYSCALL_VFS_FSTAT: {
        int fd = (int)svc_args[1];
        struct stat *stats = (struct stat *)svc_args[2];
        xipfs_syscall_vfs_fstat_t f = (xipfs_syscall_vfs_fstat_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_FSTAT];
        svc_args[0] = (int)f(fd, stats);
        break;
    }
    case XIPFS_SYSCALL_VFS_STATVFS: {
        const char *name = (const char *)svc_args[1];
        struct statvfs *stats = (struct statvfs *)svc_args[2];
        xipfs_syscall_vfs_statvfs_t f = (xipfs_syscall_vfs_statvfs_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_STATVFS];
        svc_args[0] = (int)f(name, stats);
        break;
    }
    case XIPFS_SYSCALL_VFS_FSTATVFS: {
        int fd = (int)svc_args[1];
        struct statvfs *stats = (struct statvfs *)svc_args[2];
        xipfs_syscall_vfs_fstatvfs_t f = (xipfs_syscall_vfs_fstatvfs_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_FSTATVFS];
        svc_args[0] = (int)f(fd, stats);
        break;
    }
    case XIPFS_SYSCALL_VFS_RENAME: {
        const char *from_path = (const char *)svc_args[1];
        const char *to_path = (const char *)svc_args[2];
        xipfs_syscall_vfs_rename_t f = (xipfs_syscall_vfs_rename_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_RENAME];
        svc_args[0] = (int)f(from_path, to_path);
        break;
    }
    case XIPFS_SYSCALL_VFS_NORMALIZE_PATH: {
        char *buffer = (char *)svc_args[1];
        const char *path = (const char *)svc_args[2];
        size_t buflen = (size_t)svc_args[3];
        xipfs_syscall_vfs_normalize_path_t f = (xipfs_syscall_vfs_normalize_path_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_NORMALIZE_PATH];
        svc_args[0] = (int)f(buffer, path, buflen);
        break;
    }
    case XIPFS_SYSCALL_VFS_FSYNC: {
        int fd = (int)svc_args[1];
        xipfs_syscall_vfs_fsync_t f = (xipfs_syscall_vfs_fsync_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_FSYNC];
        svc_args[0] = (int)f(fd);
        break;
    }
    case XIPFS_SYSCALL_VFS_FCNTL: {
        int fd = (int)svc_args[1];
        int cmd = (int)svc_args[2];
        int arg = (int)svc_args[3];
        xipfs_syscall_vfs_fcntl_t f = (xipfs_syscall_vfs_fcntl_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_FCNTL];
        svc_args[0] = (int)f(fd, cmd, arg);
        break;
    }
    case XIPFS_SYSCALL_VFS_MKDIR: {
        const char *name = (const char *)svc_args[1];
        mode_t mode = (mode_t)svc_args[2];
        xipfs_syscall_vfs_mkdir_t f = (xipfs_syscall_vfs_mkdir_t)
            xipfs_safe_exec_syscalls_table[XIPFS_SYSCALL_VFS_MKDIR];
        svc_args[0] = (int)f(name, mode);
        break;
    }
    default:
        return;
    }
}

#endif /* XIPFS_ENABLE_SAFE_EXEC_SUPPORT */
